# Generated by Django 5.2.6 on 2025-09-09 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linha',
            options={'ordering': ['numero'], 'verbose_name': 'Linha de Telefonia', 'verbose_name_plural': 'Linhas de Telefonia'},
        ),
        migrations.RemoveField(
            model_name='linha',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='linha',
            name='horario_fim',
        ),
        migrations.RemoveField(
            model_name='linha',
            name='horario_inicio',
        ),
        migrations.RemoveField(
            model_name='linha',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='linha',
            name='origem',
        ),
        migrations.AddField(
            model_name='linha',
            name='data_contratacao',
            field=models.DateField(default='2024-01-01', verbose_name='Data de Contratação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linha',
            name='data_vencimento',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=5, verbose_name='Dia do Vencimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linha',
            name='nome_titular',
            field=models.CharField(default='Titular não informado', max_length=100, verbose_name='Nome do Titular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linha',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='linha',
            name='operadora',
            field=models.CharField(choices=[('vivo', 'Vivo'), ('claro', 'Claro'), ('tim', 'TIM'), ('oi', 'Oi'), ('outras', 'Outras')], default='outras', max_length=20, verbose_name='Operadora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linha',
            name='tipo_plano',
            field=models.CharField(choices=[('pre', 'Pré-pago'), ('pos', 'Pós-pago'), ('controle', 'Controle')], default='pre', max_length=20, verbose_name='Tipo de Plano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linha',
            name='valor_plano',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Plano (R$)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linha',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Linha Ativa'),
        ),
        migrations.AlterField(
            model_name='linha',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='linha',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='linha',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='linha',
            name='numero',
            field=models.CharField(max_length=15, unique=True, verbose_name='Número da Linha'),
        ),
    ]
