# Generated by Django 5.2.5 on 2025-09-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhas', '0002_alter_linha_options_remove_linha_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linha',
            name='data_contratacao',
        ),
        migrations.RemoveField(
            model_name='linha',
            name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='linha',
            name='nome_titular',
        ),
        migrations.RemoveField(
            model_name='linha',
            name='operadora',
        ),
        migrations.AddField(
            model_name='linha',
            name='cnpj',
            field=models.CharField(default='', max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='linha',
            name='empresa',
            field=models.CharField(default='', max_length=100, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='linha',
            name='iccid',
            field=models.CharField(default='', max_length=25, verbose_name='ICCID'),
        ),
        migrations.AddField(
            model_name='linha',
            name='origem',
            field=models.CharField(default='', max_length=50, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='linha',
            name='rp',
            field=models.CharField(default='', max_length=50, verbose_name='RP'),
        ),
        migrations.AddField(
            model_name='linha',
            name='taxa_manutencao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Manutenção (R$)'),
        ),
    ]
