# Generated by Django 5.2.5 on 2025-09-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhas', '0003_remove_linha_data_contratacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linha',
            name='origem',
            field=models.CharField(choices=[('TT', 'TT'), ('PORTABILIDADE', 'PORTABILIDADE'), ('ESTOQUE', 'ESTOQUE'), ('MOVIMENTAR', 'MOVIMENTAR')], default='TT', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='linha',
            name='tipo_plano',
            field=models.CharField(choices=[('BLACK_VOZ_GW_800SMS', 'BLACK VOZ + GW + 800SMS'), ('BLACK_1GB_GW_800SMS', 'BLACK 1GB + GW + 800SMS'), ('BLACK_5GB_GW_800SMS', 'BLACK 5GB + GW + 800SMS = CONT. MENSAGEM + MOBILIDADE + REDE SOCIAL'), ('BLACK_10GB_GW_800SMS', 'BLACK 10GB + GW + 800SMS = CONT. MENSAGEM + MOBILIDADE + REDE SOCIAL'), ('BLACK_20GB_GW_800SMS', 'BLACK 20GB + GW + 800SMS = CONT. MENSAGEM + MOBILIDADE + REDE SOCIAL'), ('BLACK_50GB_GW_800SMS', 'BLACK 50GB + GW + 800SMS = CONT. MENSAGEM + MOBILIDADE + REDE SOCIAL'), ('BLACK_ILIMITADO_GB_GW_800SMS', 'BLACK ILIMITADO GB + GW + 800SMS = CONT. MENSAGEM + MOBILIDADE + REDE SOCIAL')], max_length=50, verbose_name='Tipo de Plano'),
        ),
    ]
