# Generated by Django 5.2.5 on 2025-09-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhas', '0004_alter_linha_origem_alter_linha_tipo_plano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linha',
            name='origem',
        ),
        migrations.AddField(
            model_name='linha',
            name='acao',
            field=models.CharField(choices=[('TT', 'TT'), ('PORTABILIDADE', 'PORTABILIDADE'), ('ESTOQUE', 'ESTOQUE')], default='TT', max_length=20, verbose_name='Ação'),
        ),
    ]
