# Generated by Django 5.2.5 on 2025-09-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhas', '0005_remove_linha_origem_linha_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linha',
            name='iccid',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='ICCID'),
        ),
    ]
