# Generated by Django 5.2.5 on 2025-11-05 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhas', '0008_alter_protocolo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=150, verbose_name='Empresa')),
                ('cnpj', models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ')),
                ('contato', models.CharField(blank=True, default='', max_length=100, verbose_name='Contato')),
                ('telefone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, default='', max_length=255, verbose_name='Endereço')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['empresa'],
            },
        ),
        migrations.AddField(
            model_name='linha',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='linhas.cliente', verbose_name='Cliente vinculado'),
        ),
    ]
