# Generated by Django 5.2.5 on 2025-11-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhas', '0009_cliente_linha_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf_dono',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='CPF do Dono'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento_dono',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento do Dono'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco_completo',
            field=models.TextField(blank=True, default='', verbose_name='Endereço completo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fantasia',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_dono',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nome do Titular / Dono'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Razão Social'),
        ),
    ]
