# Generated by Django 5.2.5 on 2025-11-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhas', '0010_remove_cliente_endereco_cliente_cpf_dono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
    ]
