# Generated by Django 5.2.5 on 2025-11-10 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhas', '0012_loginattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(help_text='Observações sobre a fidelidade da linha', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fidelidades', to='linhas.linha', verbose_name='Linha')),
            ],
            options={
                'verbose_name': 'Fidelidade',
                'verbose_name_plural': 'Fidelidades',
                'ordering': ['-criado_em'],
            },
        ),
    ]
