# Generated by Django 5.2.5 on 2025-11-17 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhas', '0013_fidelidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome Fantasia')),
                ('endereco', models.CharField(max_length=500, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('cpf_agente', models.CharField(max_length=14, verbose_name='CPF do Agente')),
                ('data_nascimento_agente', models.DateField(verbose_name='Data de Nascimento do Agente')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_empresas_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_empresa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Usuário Empresa',
                'verbose_name_plural': 'Usuários Empresas',
                'ordering': ['razao_social'],
            },
        ),
    ]
