# Generated by Django 5.2.5 on 2025-11-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhas', '0014_usuarioempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioempresa',
            name='nome_completo_agente',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome Completo do Agente'),
        ),
    ]
