# Generated by Django 5.2.6 on 2025-11-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhas', '0014_usuarioempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2, verbose_name='Tipo de Pessoa'),
        ),
    ]
