# Generated by Django 5.2.5 on 2025-11-24 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linhas', '0015_cliente_tipo_pessoa'),
        ('linhas', '0015_usuarioempresa_nome_completo_agente'),
    ]

    operations = [
    ]
