# Generated by Django 5.2.5 on 2025-11-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhas', '0016_merge_20251124_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='valor_taxa_manutencao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor da Taxa de Manutenção (R$)'),
        ),
    ]
