# Generated by Django 5.2.5 on 2025-11-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhas', '0017_cliente_valor_taxa_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fidelidade',
            name='status_protocolo',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status do Protocolo'),
        ),
        migrations.AddField(
            model_name='linha',
            name='status_protocolo',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status do Protocolo'),
        ),
    ]
