# Generated by Django 5.2.5 on 2025-11-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhas', '0018_fidelidade_status_protocolo_linha_status_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='linha',
            name='cancelada',
            field=models.BooleanField(default=False, verbose_name='Linha Cancelada'),
        ),
        migrations.AddField(
            model_name='linha',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Cancelamento'),
        ),
    ]
