from django.urls import path
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path("", RedirectView.as_view(url="login/", permanent=False)),
    path("login/", views.login_view, name="login"),
    path("listalinhas/", views.lista_linhas, name="listalinhas"),
    path("nova/", views.nova_linha, name="novalinha"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("protocolo/", views.protocolo, name="protocolo"),
    path("relatorios/", views.relatorios, name="relatorios"),
    path("clientes/novo/", views.cliente_novo, name="cliente_novo"),
    path("clientes/novo-ajax/", views.cliente_create_ajax, name="cliente_create_ajax"),
    path("relatorios/export/linhas-cycle/", views.export_linhas_cycle_csv, name="export_linhas_cycle_csv"),
    path("relatorios/export/linhas-cycle-xlsx/", views.export_linhas_cycle_xlsx, name="export_linhas_cycle_xlsx"),
    path("relatorios/export/protocolos-pendentes/", views.export_protocolos_pendentes_csv, name="export_protocolos_pendentes_csv"),
    path("configuracoes/", views.configuracoes, name="configuracoes"),
    path("configuracoes/desbloquear-usuario/", views.desbloquear_usuario, name="desbloquear_usuario"),
    path("editar/<int:pk>/", views.editar_linha, name="editarlinha"),
    path("excluir/<int:pk>/", views.excluir_linha, name="excluirlinha"),
    path("detalhes/<int:pk>/", views.detalhes_linha, name="detalheslinha"),
    path("buscar-linhas-estoque/", views.buscar_linhas_estoque, name="buscar_linhas_estoque"),
    path("buscar-cliente-cnpj/", views.buscar_cliente_por_cnpj, name="buscar_cliente_por_cnpj"),
    path("buscar-cnpj-api/", views.buscar_cnpj_api_externa, name="buscar_cnpj_api_externa"),
    path("test-cnpj-api/", views.test_cnpj_api_view, name="test_cnpj_api"),
    path("debug-cnpj-button/", views.debug_cnpj_button_view, name="debug_cnpj_button"),
    path("debug-cnpj-complete/", views.debug_cnpj_complete_view, name="debug_cnpj_complete"),
    path("buscar-empresas/", views.buscar_empresas, name="buscar_empresas"),
    path("buscar-clientes/", views.buscar_clientes, name="buscar_clientes"),
    path("autocomplete-cnpj/", views.autocomplete_cnpj, name="autocomplete_cnpj"),
    path("listar-rps-cliente/", views.listar_rps_cliente, name="listar_rps_cliente"),
    path("fidelidade/", views.fidelidade, name="fidelidade"),
    path("buscar-linha-dados/", views.buscar_linha_dados, name="buscar_linha_dados"),
    path("configuracoes/criar-usuario/", views.criar_usuario_empresa, name="criar_usuario_empresa"),
    path("configuracoes/listar-usuarios/", views.listar_usuarios_empresa, name="listar_usuarios_empresa"),
    path("configuracoes/toggle-usuario-status/", views.toggle_usuario_status, name="toggle_usuario_status"),
    path("configuracoes/visualizar-usuario/<int:user_id>/", views.visualizar_usuario, name="visualizar_usuario"),
    path("configuracoes/editar-usuario/<int:user_id>/", views.editar_usuario, name="editar_usuario"),
    path("configuracoes/excluir-usuario/<int:user_id>/", views.excluir_usuario, name="excluir_usuario"),
    path("configuracoes/alterar-senhas/", views.alterar_senhas, name="alterar_senhas"),
    path("configuracoes/alterar-senha-usuario/", views.alterar_senha_usuario, name="alterar_senha_usuario"),
    path("cadastro-empresa/", views.cadastro_empresa, name="cadastro_empresa"),
    path("listar-empresas/", views.listar_empresas, name="listar_empresas"),
    path("preview-arquivo-linhas/", views.preview_arquivo_linhas, name="preview_arquivo_linhas"),
    path("processar-lista-estoque/", views.processar_lista_estoque, name="processar_lista_estoque"),
]